---
title: "Homework"
---

+--------------+-----------------------------------------------+-----------+-------+----------------------------------------------------+
| Assignment # | Description                                   | Due Date  | Value | Solutions                                          |
+==============+===============================================+===========+=======+====================================================+
|    0/1       | Review/Foundations.  Probability, a little    | 2/1/2019  |  1    |                                                    |
|              | calculus, and R.                              |           |       |                                                    |
|              |                                               |           |       |                                                    |
|              | Written part:                                 |           |       |                                                    |
|              | [pdf](homework/ps0/ps0_written.pdf)           |           |       |                                                    |
|              | [Rmd](homework/ps0/ps0_written.Rmd)           |           |       |                                                    |
|              |                                               |           |       |                                                    |
|              | R part: Data Camp assignments posted now.     |           |       |                                                    |
|              | Remainder via GitHub.                         |           |       |                                                    |
+--------------+-----------------------------------------------+-----------+-------+----------------------------------------------------+
|    2         | Chapter 7 Sections 7.1 through 7.3.           | 4pm,      |  1    |                                                    |
|              |                                               | 2/8/2019  |       |                                                    |
|              |                                               |           |       |                                                    |
|              | Written part:                                 |           |       |                                                    |
|              | [pdf](homework/ps2/ps2_written.pdf)           |           |       |                                                    |
|              | [Rmd](homework/ps2/ps2_written.Rmd)           |           |       |                                                    |
|              |                                               |           |       |                                                    |
|              | R part: Assigned on GitHub.                   |           |       |                                                    |
+--------------+-----------------------------------------------+-----------+-------+----------------------------------------------------+
|    3         | Chapter 8 Sections 8.1 through 8.5.           | 4pm,      |  1    |                                                    |
|              |                                               | 2/22/2019 |       |                                                    |
|              |                                               |           |       |                                                    |
|              | Written part:                                 |           |       |                                                    |
|              | [pdf](homework/ps3/ps3_written.pdf)           |           |       |                                                    |
|              | [Rmd](homework/ps3/ps3_written.Rmd)           |           |       |                                                    |
|              |                                               |           |       |                                                    |
|              | R part: Assigned on GitHub.                   |           |       |                                                    |
+--------------+-----------------------------------------------+-----------+-------+----------------------------------------------------+
|    4         | Chapter 8 Sections 8.1 through 8.5.           | 4pm,      |  1    |                                                    |
|              |                                               | 3/1/2019  |       |                                                    |
|              |                                               |           |       |                                                    |
|              | Written part:                                 |           |       |                                                    |
|              | [pdf](homework/ps4/ps4_written.pdf)           |           |       |                                                    |
|              | [Rmd](homework/ps4/ps4_written.Rmd)           |           |       |                                                    |
|              |                                               |           |       |                                                    |
|              | R part: Assigned on GitHub.                   |           |       |                                                    |
+--------------+-----------------------------------------------+-----------+-------+----------------------------------------------------+
|    5         | Chapter 8 Section 8.6.                        | 4pm,      |  1    |                                                    |
|              |                                               | 3/8/2019  |       |                                                    |
|              |                                               |           |       |                                                    |
|              | Written part:                                 |           |       |                                                    |
|              | [pdf](homework/ps5/ps5_written.pdf)           |           |       |                                                    |
|              | [Rmd](homework/ps5/ps5_written.Rmd)           |           |       |                                                    |
|              |                                               |           |       |                                                    |
|              | R part: Assigned on GitHub.                   |           |       |                                                    |
+--------------+-----------------------------------------------+-----------+-------+----------------------------------------------------+

