---
title: "Mathematical Statistics"
---

**Instructor:** Evan Ray

**Email:** eray@mtholyoke.edu

**Office:** Clapp 404C

**Office Hours:** Regularly scheduled office hours at times to be determined.  These are times I guarantee I will be in my office and available, but that should **not** be interpreted as indicating that these are the only times I'm willing to meet.  Please do not hesitate to contact me to set up appointments for additional office hours at any time!!

**Space for Collaboration:** We don't have a TA assigned to this class, but I do encourage you to meet up to work on problems together.  Clapp 416 has been reserved and will be open for you to work together on Tuesday evenings.  If it would be helpful to have another space or time reserved, let me know and we can set that up.

**Piazza:** We have a Piazza page at [https://piazza.com/mtholyoke/spring2019/stat343](https://piazza.com/mtholyoke/spring2019/stat343).  You can ask and answer questions there, anonymously if you want, and everyone in the class will be able to see and contribute to the answers.

**Syllabus:** [pdf](syllabus/syllabus_stat_343.pdf)

Please use the navigation menu above to go to the schedule, homework assignments, resources, and materials related to quizzes and exams.
