---
title: "Schedule"
---

**Click on the text like "Week 1: Jan 22 -- 25" to expand or collapse the items we covered in that week.**

I will fill in more detail and provide links to lecture notes and labs as we go along.  Items for future dates are tentative and subject to change.

```{r, echo = FALSE}
make_week_box <- function(id, open, title, contents) {
  cat('
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingOne">
<h5 class="mb-0">
<a data-toggle="collapse" href="#',
id,
'" aria-expanded="true" aria-controls="collapseOne">
',
title,
'</a>
</h5>
</div>

<div id="',
id,
'" class="collapse',
ifelse(open, " in", ""),
'">
<div class="panel-body">
',
contents,
'
</div>
</div>
</div>',
  sep = "")
}
```

```{r, echo = FALSE, results='asis'}
make_week_box("week1", FALSE, "Week 1: Jan 22 -- 25",
"
* Introduction; review of topics from probability; properties of the sample mean for a simple random sample from a finite populaiton
 
#### Wed, Jan 23

 * **In class**, we will work on: Overview and review
    * Discuss [syllabus](syllabus/syllabus_stat_343.pdf), overview of course
    * Review of prerequisites
        * Topics from probability: [pdf](resources/probability/probability.pdf) (also posted on resources page)
        * Practice examples for probability: [pdf](materials/20180123_probability/probability_practice.pdf)
        * Common probability distributions: [pdf](resources/probability/probability_distributions.pdf) (also posted on resources page; you don't need to memorize this material)
        * Topics from calculus (not discussed today, please review after class): [pdf](resources/calculus/calculus.pdf) (also posted on resources page)
 * **After class**, please do the following:
    * **Register for GitHub** [here](https://github.com) if you haven't already; I will ask you to provide your GitHub user name in the questionairre below.
    * **Fill out** a brief [questionnairre](https://goo.gl/forms/qFlzOcikqxAkDrJE2)
    * **Fill out** this brief [poll about when my office hours should be held](http://whenisgood.net/n4ahdz3)
    * **Sign up** for our class at Piazza (anonymous question and answer forum): [https://piazza.com/mtholyoke/spring2019/stat343](https://piazza.com/mtholyoke/spring2019/stat343)
    * **Reading**
        * Review the prerequisite material from probability and calculus.  If there are any topics from probability or calculus that you don't have memorized, please start memorizing them.  This will make the rest of this class go much more smoothly for you.  If you have any questions on this material, please don't hesitate to ask me in office hours or on Piazza.  I am happy to help with this material.
        * Over the next few classes we will cover material from Sections 7.1 - 7.3 of the text.  Give those sections in the book a brief skim.
    * **Homework 0** due Wed, Jan 30

#### Fri, Jan 25
 * **In class**, we will work on: Sections 7.1, 7.2, 7.3.1, and 7.3.2 (mostly lecture)
    * Last two probability examples from last class
    * Briefly talk through the \"common probability distributions\" handout
    * Motivating example for Chapter 7: [pdf](materials/20180125_srs/srs_hospitals.pdf)
    * Definitions from Chapter 7 (some on motivating example handout): population parameter, statistic, estimator, estimate, simple random sample, sampling distribution, bias, variance, mean squared error
    * Start on some derivations of the expected value, variance, and MSE of the sample mean based on a simple random sample from a finite population.
    * If time (unlikely), start on estimating the population variance based on a simple random sample from a finite population.
    * Lecture notes for Sections 7.1, 7.2, 7.3.1, and 7.3.2: [pdf](materials/20180125_srs/lecture_notes.pdf)
    * Set up git on RStudio (if you took Stat 340 with me, you can leave early)
 * **After class**, please do the following:
    * Start memorizing any definitions from today's class that you don't know yet.
    * **Problem Set 0** due Wed, Jan 30
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week2", FALSE, "Week 2: Jan 28 -- Feb 1",
"
Section 7.3.3 (see Stat 344SM, survey sampling, for the rest of Chapter 7 and much more); start on Chapter 8

#### Mon, Jan 28
 * **In Class**, we will work on: Sections 7.1, 7.2, 7.3.1, and 7.3.2 (mostly lecture, some worked examples)
    * Finish stuff from Sections 7.2, 7.3.1, and 7.3.2 that we didn't get to on Friday.
 * **After class**, please do the following:
    * **Problem Set 0** due Wed, Jan 30

#### Wed, Jan 30
 * **In Class**, we will work on: Section 5.3 and part of 7.3.3 (mostly lab)
    * Central Limit Theorem, more on the sampling distribution of the sample mean
    * Lab 1 on GitHub
    * Topics from R:
        * `for` loops: [pdf](materials/20180130_sampling_dist/for_loops.pdf)
        * `dplyr::sample_n`
 * **After class**, please do the following:
    * **Problem Set 0** due Fri, Feb 1

#### Fri, Feb 1
 * **Problem Set 0 due today!!**
 * **In Class**, we will work on: Section 7.3.3
    * Mean Squared Error = Bias$^2$ + Variance.  Lecture notes: [pdf](materials/20190201_mse/20190201_mse_lecture_notes.pdf)
    * Finish lab from last time
 * **After class**, please do the following:
    * **Problem Set 1** due Fri, Feb 15
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week3", FALSE, "Week 3: Feb 4 -- 8",
"

#### Mon, Feb 4
 * **In Class**, we will work on: Section 7.3.3
    * A first look at confidence intervals for a population mean based on a simple random sample.  [pdf](materials/20190204_srs_ci_lecture_notes/20190204_lecture_notes.pdf)  (not on the lecture notes but discussed in class are the coverage probability and nominal coverage probability of a confidence interval)
    * R topics: Logical operations on vectors, mutate and summarize [pdf](resources/R/mutate_summarize.pdf)
    * Lab 2: confidence intervals for simple random sampling
 * **After class**, please do the following:
    * **Problem Set 1** due Fri, Feb 15

#### Wed, Feb 6
 * **In Class**, we will work on: Finish Section 7.3.3
    * Finish confidence intervals lab from last class
    * If you finish early, free time or work on homework
 * **After class**, please do the following:
    * **Problem Set 1** due Fri, Feb 15

#### Fri, Feb 8
 * **In Class**, we will work on: Start on Sections 8.1 through 8.5
    * Introductory worksheet, friend or foe: [pdf](materials/20190208_mle/20180208_mle_friend_or_foe.pdf)
    * Some plots to go with the introductory worksheet: [pdf](materials/20190208_mle/20180208_mle_friend_or_foe_2.pdf)
        * Rmd file in case you want to see code for making the plots: [Rmd](materials/20190208_mle/20180208_mle_friend_or_foe_2.Rmd)
    * Defined the likelihood function, log-likelihood function, maximum likelihood estimator, maximum likelihood estimate
    * Argued that the parameter value that maximizes the log-likelihood also maximizes the likelihood, since log is an increasing function.
    * Reviewed some calculus related to finding a maximum of a univariate function
 * **After class**, please do the following:
    * **Problem Set 1** due Fri, Feb 15
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week4", FALSE, "Week 4: Feb 11 -- 15",
"

#### Mon, Feb 11
 * **In Class**, we will work on: Sections 8.1 through 8.5
    * Finish first example of maximum likelihood from last class
    * Second example: [pdf](materials/20190211_mle/20190211_mle_saplings.pdf) Solutions: [pdf](materials/20190211_mle/20190211_mle_saplings_solutions.pdf).  See also R part and solutions posted as lab 3 on GitHub.

#### Wed, Feb 13
 * **In Class**, we will work on: Sections 8.1 through 8.5
    * Maximum likelihood for models with more than 1 parameter.
    * Example of normal distribution.  Lecture notes: [pdf](materials/20190213_mle_slr/lecture_notes_normal_mle.pdf)
    * Example of simple linear regression, variance known
        * Handout: [pdf](materials/20190213_mle_slr/20190213_mle_slr.pdf)
        * Solutions: [pdf](materials/20190213_mle_slr/20190213_mle_slr_solutions.pdf).  Solutions to R part posted on GitHub.

#### Fri, Feb 15
 * **In Class**, we will work on: Sections 8.1 through 8.5
    * Wrap up examples from last class
        * Talk through the likelihood for the normal distribution model with 2 unknown parameters: [html](materials/20190215/normal_likelihood.html) [Rmd](materials/20190215/normal_likelihood.Rmd)
        * Highlights from solutions for simple linear regression handout, posted for Wed, Feb 13
    * Review of Taylor's Theorem.  See last 2 pages of handout about calculus from first day, also posted on resources page.
    * Introduce methods for numerical maximization of functions.  Slides: [pdf](materials/20190215/Newton%20Raphson%20for%20Optimization.pdf)
        * Note that on slide 5 I should have had lower case $\\ell$ (for the log-likelihood) rather than upper case $L$.
    * Start Lab 5, on numeric optimization via Newton's method; posted on GitHub
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week5", FALSE, "Week 5: Feb 18 -- 22",
"

#### Mon, Feb 18
 * **In Class**, we will work on:
    * Finish Lab 5

#### Wed, Feb 20
 * **In Class**, we will work on:
    * Numeric maximum likelihood in Stan
        * Example [pdf](materials/20190220_stan_optimization/20190220_stan_optimization.pdf)
        * Lab 6
    * Prepare for next class: Lab 7a

#### Fri, Feb 22
 * **In Class**, we will work on:
    * **Before class**, please complete Lab 7a!!  Note that in the calls to `qbeta`, you will need to change the \`shape2\` parameter to \`b\`.  Your revised code will look like this:
\`\`\`{r}
qbeta(c(0.25, 0.75), shape1 = a, shape2 = b)
qbeta(c(0.05, 0.95), shape1 = a, shape2 = b)
\`\`\`
    * Bayesian Estimation: Section 8.6
        * Lecture notes: [pdf](materials/20190222_binomial_bayes/lecture_notes.pdf)
        * Lab 7b
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week6", FALSE, "Week 6: Feb 25 -- Mar 1",
"

#### Mon, Feb 25
 * **In Class**, we will work on: Section 8.6
    * Examples of Bayesian inference with conjugate priors: [pdf](materials/20190225_bayes_practice/20190225_bayes_practice.pdf).  Solutions: [pdf](materials/20190225_bayes_practice/20190225_bayes_practice_solutions.pdf).

#### Wed, Feb 27
 * **In Class**, we will work on: Section 8.6
    * Lab 8

#### Fri, Mar 1
 * **In Class**, we will work on:
    * Set up for MCMC: Limits of conjugate priors for handling normal distributions.  Notes: [pdf](materials/20190301_mcmc/bayes_normal_notes.pdf)
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week7", FALSE, "Week 7: Mar 4 -- 8",
"

#### Mon, Mar 4
 * **In Class**, we will work on:
    * Justification of numerical integration using the law of large numbers.  Lecture notes: [pdf](materials/20190301_mcmc/numerical_integration_notes.pdf)
    * MCMC for Bayesian inference using Stan.
        * Handout: [pdf](materials/20190301_mcmc/20190225_bayes_MCMC_Metropolis.pdf)
        * Lab 9 posted on GitHub
    * MCMC for Bayesian inference.
        * Reading 1: the discussion of the law of large numbers and its application for numerical integration, discussed in Section 5.2 of Rice.
        * Reading 2 (optional?): I've posted a chapter from Introduction to Statistical Thought by Michael Lavine.  This goes into more depth than we will, but it's the most readable less-than-book-length introduction to this topic at an undergraduate level that I have found.  It is linked to from the resources page: http://www.evanlray.com/stat343_s2019/resources.html

#### Wed, Mar 6
 * **In Class**, we will work on:
    * Large-sample normal approximation to the posterior distribution.
        * Motivating examples from previous classes: [pdf](materials/20190306_normal_approx_posterior/20190306_normal_approx_posterior.pdf)
        * Proof step 1: For large n, the prior's effect on the posterior is irrelevant in comparison to the likelihood.  Motivating (??) pictures: [pdf](materials/20190306_normal_approx_posterior/20190306_log_posterior_contributions.pdf)
        * Proof step 2: Second order Taylor series approximation to log-likelihood.  Lecture notes: [pdf](materials/20190306_normal_approx_posterior/lecture_notes.pdf)

#### Fri, Mar 8
 * **In Class**, we will work on:
    * Wrap up of lab 9; solutions are posted on GitHub
    * Examples of large-sample normal approximations to the posterior
        * Binomial examples/motivation: [pdf](materials/20190308_normal_approx_posterior_examples/binomial_approx_posterior.pdf)
        * Large sample CI example (see lab 10): [pdf](materials/20190308_normal_approx_posterior_examples/20180308_large_sample_ci.pdf)
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week8", FALSE, "Week 8: Mar 11 -- 15",
"
#### Spring Break: safe travels!
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week9", FALSE, "Week 9: Mar 18 -- 22",
"

#### Mon, Mar 18
 * **In Class**, we will work on: ideas from Section 8.5.3, borrowed the idea of the likelihood ratio from Section 9.1.
    * Exact confidence intervals, based on exact form of sampling distribution of a statistic. Lecture notes: [pdf](materials/20190318_large_sample_information/lecture_notes.pdf)
    * Develop some intuition for Fisher information: [pdf](materials/20190318_large_sample_information/20180318_large_sample_information.pdf)

#### Wed, Mar 20
 * **In Class**, we will work on:
    * Finish intuition handout from last class
    * Lots of lecture about Fisher Information and Observed Fisher Information, large-sample normal approximations to the sampling distribution of the MLE in terms of information; confidence intervals from the large sample normal approximation; Poisson example.  Lecture notes: [pdf](materials/20190320_large_sample_ci/lecture_notes.pdf)
    * Handout to go with Poisson example: [pdf](materials/20190320_large_sample_ci/20180320_poisson_large_sample_ci.pdf)

#### Fri, Mar 22
 * **In Class**, we will work on:
    * **Midterm** on PS1 through PS5
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week10", FALSE, "Week 10: Mar 25 -- 29",
"

#### Mon, Mar 25
 * **In Class**, we will work on:
    * Practice with large sample approximations to sampling distribution of the MLE: [pdf](materials/20190325_large_sample_practice/20190325_pareto_mle_sampling.pdf)
    * Start Lab 12

#### Wed, Mar 27
 * **In Class**, we will work on:
    * Some large-sample results about maximum likelihood estimators.  Consistency, Cramer-Rao Lower Bound, efficiency, shrinkage estimators.  Lecture notes: [pdf](materials/20190327_large_sample_results/lecture_notes_consistency_CRLB_shrinkage.pdf)
    * Finish Lab 12, Start Lab 11

#### Fri, Mar 29
 * **In Class**, we will work on:
    * Shrinkage estimators.  No lecture notes, but we talked about how the posterior mean for the mean of a normal distribution and the parameter theta for a binomial distribution can both be viewed as an appropriately weighted average of the prior mean and the data mean.
    * Finish old labs
    * Start an example about practice with MSE, which will be due for homework: [pdf](materials/20190329_MSE_practice/20190329_MSE_practice.pdf)
    * Start Lab 13, which will be due for homework.
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week11", TRUE, "Week 11: Apr 1 -- 5",
"

#### Mon, Apr 1
 * **In Class**, we will work on:
    * Bootstrap estimation of a sampling distribution.  Handout: [pdf](materials/20190401_bootstrap/20180401_bootstrap.pdf)
    * Lab 14

#### Tue, Apr 3
 * **In Class**, we will work on:
    * Bootstrap confidence intervals.  Handout (NOTE: the version I distributed in class wasn't quite right on the last page.  Corrected version here.): [pdf](materials/20190403_bootstrap_CIs/20180403_bootstrap_CIs.pdf)
    * Lab 15

#### Fri, Apr 5
 * **In Class**, we will work on:
    * Start on hypothesis testing; Chapter 9
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week12", FALSE, "Week 12: Apr 8 -- 12",
"

#### Mon, Apr 8
 * **In Class**, we will work on:

#### Wed, Apr 10
 * **In Class**, we will work on:

#### Fri, Apr 12
 * **In Class**, we will work on:
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week13", FALSE, "Week 13: Apr 15 -- 19",
"

#### Mon, Apr 15
 * **In Class**, we will work on:

#### Wed, Apr 17
 * **In Class**, we will work on:

#### Fri, Apr 19
 * **In Class**, we will work on:
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week14", FALSE, "Week 14: Apr 22 -- 26",
"

#### Mon, Apr 22
 * **In Class**, we will work on:

#### Wed, Apr 24
 * **In Class**, we will work on:

#### Fri, Apr 26
 * **In Class**, we will work on:
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week15", FALSE, "Week 15: Apr 29 -- 30",
"

#### Mon, Apr 29
 * **In Class**, we will work on:
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("finals", TRUE, "Final Exams: Fri, May 3 at 7pm -- Tue, May 7 at noon",
"We will have a cumulative final exam.
"
  )
```
