---
title: "20180125 - Friend or Foe"
author: "Evan L. Ray, adapted from Allan Rossman and Beth Chance"
date: "Janary 25, 2018"
output:
  pdf_document:
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Do children who are less than a year old recognize the difference between nice, friendly behavior as
opposed to mean, unhelpful behavior? Do they make choices based on such behavior? In a
study reported in the November 2007 issue of Nature, researchers investigated whether infants
take into account an individual's actions towards others in evaluating that individual as appealing
or aversive (Hamlin, Wynn, and Bloom, 2007).

In one component of the study, sixteen 10-month-old infants were shown a "climber" character
(a piece of wood with "google" eyes glued onto it) that
could not make it up a hill in two tries. Then they were alternately shown two scenarios for the
climber's next try, one where the climber was pushed to the top of the hill by another character
("friend") and one where the climber was pushed back down the hill by another character
("foe"). The infant was alternately shown these two scenarios several times. Then the child was
presented with both pieces of wood (representing the friend and the foe) and asked to pick one to
play with. Videos of this study are available at websites for the UBC Center for Infant Cognition Lab (<http://cic.psych.ubc.ca/example-stimuli/>) and the Yale Infant Cognition Center (<https://campuspress.yale.edu/infantlab/>).

The "climber" character was a yellow triangle; helper and hinderer were a red square and a blue circle.  Which of the square and the circle was the helper and which was the hinderer was determined randomly for each baby.  Also randomized were which event (helping or hindering) they observed first and the positions of helper and hinderer when presented to the infants (on left or right).

Let the random variable $X$ denote the number of babies (out of the total of 16) who preferred the helpful toy.

#### 1. What statistical model would be appropriate for the distribution of the number of babies who preferred the helpful toy?

\vspace{0.5cm}

$X$ $\sim \,$

#### 2. The researchers are interested in the underlying proportion of 10-month-old infants who express a preference for the helpful character.  How does this relate to the statistical model you wrote down in part 1?

\newpage

#### 3. Write down the probability mass function for $X$, based on the model you specified in part 1.

\vspace{3cm}

#### 4. When they conducted this experiment, the researchers observed a particular value, $x$, for the number of babies in the sample who selected the helpful toy.  (I'll tell you what $x$ was in a minute, but for now let's stick with using symbols.)  Write down the likelihood function $\mathcal{L}(p | x)$ for the unknown model parameter $p$, conditional on the observed data $x$.

\vspace{4cm}

#### 5. This problem is one example where it will be easier to work with the log-likelihood instead of the likelihood.  Write down the log-likelihood function $L(p | x)$.

\newpage

#### 6. Prove that the maximum likelihood estimator of $p$ is the sample proportion, $\hat{p}_{MLE} = \frac{x}{n}$.

Your life will be easier if you do this by working with the log-likelihood function.  Your proof has two steps.

##### (a) Find a critical point.

We know that the maximum of the (log-)likelihood function must occur at a critical point, where $\frac{d}{d \, p} L(p | x) = 0$. Calculate the derivative of the log-likelihood function with respect to $p$, set the result equal to $0$, and solve for the critical point.

\vspace{8cm}

##### (b) Verify that the critical point is at a maximum of the likelihood function.

Recall that the critical point you found in part (a) is a local maximum if the second derivative of the log-likelihood function evaluated at that critical point is negative, and is guaranteed to be a global maximum if the second derivative is negative everywhere. Verify that this condition holds.

\newpage

#### 7. The researchers found that $x=14$ of the 16 infants in the study selected the nice toy.  Find the maximum likelihood estimate of $p$.

